### ISSUE TITLE
Can sparklyr.sedona be officially part of Apache Sedona?

### ISSUE THREAD

**Issue by yitao-li** [r-spark/sparklyr.sedona#39]
Context: https://github.com/harryprince/geospark/issues/20

Questions:
- Whether sparklyr.sedona will have regular CRAN releases (just like any other normal R package does) or whether it will be released as part of Apache Sedona code base but not through CRAN? (for example currently SparkR is in the latter category which IMHO is non-ideal, while mlflow R client is in the former category)
- Whether it's releases will be tied to the release cycle of Apache Sedona? (for example currently mlflow R client releases are tied to the release cycle of the rest of the mlflow, which may be in some way restrictive in term of how often major versions of mlflow R client can be released... do we want to follow the same model or not for sparklyr.sedona)
- Whether sparklyr.sedona should be designed to work with multiple versions of Spark? (feels like answer to this should be a resounding "yes" as sparklyr itself is aiming to be maximally compatible with multiple Spark versions)
- Whether sparklyr.sedona should attempt to be maximally compatible with multiple versions of Apache Sedona? (answer might be no if Sedona has drastic interface changes from one version to another)

**Comment by etiennebr** [comment]
Awesome project! I believe @jiayuasu might be able to help.

**Comment by yitao-li** [comment]
@jiayuasu Sounds great! 👍 I'll work on migrating sparklyr.sedona repo soon.

**Comment by yitao-li** [comment]
@jiayuasu I have created a PR for integrating `sparklyr.sedona` with the main apache/incubator-sedona repo in https://github.com/apache/incubator-sedona/pull/521

Please let me know what you think.

**Comment by yitao-li** [comment]
Happy to see this went exactly as planned. Great work, everyone :+1:
